### ISSUE TITLE
Include tests in sdist

### ISSUE THREAD

**Issue by jayvdb** [useblocks/tox-envreport#1]
Please include the tests in the sdist uploaded to PyPI, to help with distro packaging, and also creating a GitHub tag as part of each release would be helpful.

**Comment by danwos** [comment]
GitHub tag is done.
As there are no test cases currently, there is also nothing to include :(

I hope I will find some time to fix this with the next release...

**Comment by jayvdb** [comment]
Ah, a hopeful empty tests directory ;-)

A simple approach for testing would be using bats. https://github.com/bats-core/bats-core

Or tox testenvs invoking tox like https://github.com/pglass/tox-pip-version

**Comment by danwos** [comment]
Ohh thanks for the hints.
This will help a lot getting started!
